# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8fae009cb4c3ed844abfd69335a8bf0fd9fc0afea15dfd569dddc6c9e6ba51cdd2fbe955d0c5d295214c8861c67c593a2d6d7f453e72da00f58f74dbaaaf96b

test:
  secret_key_base: 78b51ff4191d23b624bf0e5f609cd07b3a0d12c84b8bf88aa7dc673c92c93ef4154cb358ed19d6ff14aa7acb823e3034a536596466e43e699833b0f601b2f635

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
